name: Apply GitFlow Ruleset

on:
  push:
    branches:
      - main

jobs:
  apply-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Apply ruleset
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_FLOW_PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/rulesets" \
            -d @.github/rulesets/gitflow-ruleset.json
            