name: Branch Naming Convention

on:
  push:
    branches-ignore:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          if [[ ${{ github.head_ref }} =~ ^feature/ ]]; then
            echo "Feature branch detected. Branch name is valid."
          elif [[ ${{ github.head_ref }} =~ ^bugfix/ ]]; then
            echo "Bugfix branch detected. Branch name is valid."
          elif [[ ${{ github.head_ref }} =~ ^release/ ]]; then
            echo "Release branch detected. Branch name is valid."
          elif [[ ${{ github.head_ref }} =~ ^hotfix/ ]]; then
            echo "Hotfix branch detected. Branch name is valid."
          else
            echo "Branch name does not follow the naming conventions."
            exit 1
          fi
