name: Check Commit Messages for Issue References

on: [push, pull_request]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Adjusts commit history depth based on the trigger event

      - name: Check commits for issue references
        run: |
          commits=$(git log --format=%B -n 2 | grep -oP '(?<=#)\d+')
          echo "Found issues in commits: $commits"
          for issue in $commits; do
            # Skip checking for automation commits
            if [[ "$GITHUB_ACTOR" == "github-actions[bot]" ]]; then
              echo "Skipping check for automation commit"
              continue
            fi

            echo "Checking issue #$issue"
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/$issue)
            state=$(echo $response | jq -r .state)
            assignee=$(echo $response | jq -r .assignee.login)
            echo "Issue #$issue - State: $state, Assignee: $assignee"

            if [ "$state" != "open" ] || [ "$assignee" != "expected_assignee" ]; then
              echo "Issue #$issue does not meet the criteria"
              exit 1
            fi
          done
