name: Develop Branch Merge Validation

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^(release/|hotfix/) ]]; then
            echo "Only release or hotfix branches can merge into develop."
            exit 1
          fi
