name: Enforce Branch Naming Convention

on:
  create:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/heads/(feature|hotfix|release)/.+ ]]; then
            echo "Branch name does not follow the GitFlow naming convention (feature/, hotfix/, release/)."
            exit 1
          fi
