name: Feature Branch Validation

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature/')
    steps:
      - name: Check target branch
        run: |
          if [ "${{ github.base_ref }}" != "develop" ]; then
            echo "Feature branches must target the develop branch."
            exit 1
          fi
