name: Hotfix Branch Validation

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'hotfix/')
    steps:
      - name: Check target branch
        run: |
          if [ "${{ github.base_ref }}" != "main" ] && [ "${{ github.base_ref }}" != "develop" ]; then
            echo "Hotfix branches must target the main or develop branch."
            exit 1
          fi
